import { ClientRecord, LeadRecord, MaintenancePlan } from '../types/agency';

export const agencyPricing = {
  starter: {
    id: 'starter' as const,
    name: 'Starter Website',
    price: '₹4,999',
    numericPrice: 4999,
    target: 'Small shops, local services, and single-service businesses',
    pages: '1–3 Pages',
    features: [
      '1–3 Responsive pages',
      'Mobile-first layout & typography',
      'Business profile, services & about section',
      'Direct WhatsApp chat button',
      'Interactive Google Maps embed',
      'Contact section & social links',
      'Basic on-page SEO setup',
      'Vercel cloud deployment'
    ]
  },
  business: {
    id: 'business' as const,
    name: 'Business Website',
    price: '₹9,999',
    numericPrice: 9999,
    popular: true,
    badge: 'MOST POPULAR',
    target: 'Restaurants, cafes, bakeries, salons, gyms, and growing local businesses',
    pages: '5–7 Pages',
    features: [
      '5–7 Premium responsive pages',
      'Custom branding & color palette',
      'Interactive digital menu or product catalog',
      'High-resolution photo gallery',
      'Direct WhatsApp ordering / booking links',
      'Interactive Google Maps with directions',
      'Live opening hours widget',
      'Contact & enquiry form with validation',
      'Social media integration',
      'Local SEO setup, Sitemap.xml & Robots.txt',
      'Custom domain connection (.com / .in)',
      'Google Search Console setup guidance'
    ]
  },
  proWebApp: {
    id: 'pro-web-app' as const,
    name: 'Pro Web Application',
    price: '₹19,999+',
    numericPrice: 19999,
    target: 'Businesses requiring dynamic databases, admin dashboards, and custom workflows',
    pages: 'Custom Architecture',
    features: [
      'Modern React frontend application',
      'Secure Backend API & database architecture',
      'Role-based authentication & admin dashboard',
      'Full CRUD (Create, Read, Update, Delete) capability',
      'Custom client enquiry & order workflows',
      'User management & customer directory',
      'Automated receipt / summary generator',
      'Third-party API & service integration',
      'Scalable cloud deployment with database backups'
    ]
  },
  'pro-web-app': {
    id: 'pro-web-app' as const,
    name: 'Pro Web Application',
    price: '₹19,999+',
    numericPrice: 19999,
    target: 'Businesses requiring dynamic databases, admin dashboards, and custom workflows',
    pages: 'Custom Architecture',
    features: [
      'Modern React frontend application',
      'Secure Backend API & database architecture',
      'Role-based authentication & admin dashboard',
      'Full CRUD (Create, Read, Update, Delete) capability',
      'Custom client enquiry & order workflows',
      'User management & customer directory',
      'Automated receipt / summary generator',
      'Third-party API & service integration',
      'Scalable cloud deployment with database backups'
    ]
  },
  custom: {
    id: 'custom' as const,
    name: 'Custom Project',
    price: 'Request a Quote',
    numericPrice: 0,
    target: 'Complex multi-branch platforms or unique digital solutions',
    pages: 'Tailored Scope',
    features: [
      'Dedicated technical project roadmap',
      'Custom microservices or multi-tenant database',
      'Multi-location business management',
      'Milestone-based delivery & testing',
      'Direct priority WhatsApp & phone support'
    ]
  }
};

export const maintenancePlans: MaintenancePlan[] = [
  {
    id: 'website-care',
    name: 'Website Care',
    price: '₹1,499/mo',
    numericMonthlyPrice: 1499,
    tagline: 'Essential maintenance for hands-off peace of mind.',
    features: [
      'Hosting & Vercel deployment management',
      'Continuous uptime & SSL status monitoring',
      'Minor content changes (menu items, prices, banners)',
      'Image uploads & gallery updates (up to 5 per month)',
      'Small UI bug fixes & browser compatibility checks',
      'Technical support via WhatsApp'
    ],
    disclaimers: [
      'Does not include major feature rebuilds or new page development',
      'Domain renewal fee is billed directly by client registrar'
    ]
  },
  {
    id: 'advanced-care',
    name: 'Advanced Website Care',
    price: '₹2,999/mo',
    numericMonthlyPrice: 2999,
    badge: 'RECOMMENDED FOR ACTIVE SITES',
    tagline: 'Comprehensive maintenance, local SEO care, and monthly health review.',
    features: [
      'Everything in Website Care included',
      'Google Business Profile maintenance assistance',
      'Google Search Console crawl error monitoring',
      'Basic local SEO tracking & keyword monitoring',
      'Monthly website health & performance review report',
      'More frequent content updates (up to 15 per month)',
      'Core Web Vitals & mobile load speed optimizations',
      'Priority same-day WhatsApp support'
    ],
    disclaimers: [
      'We do NOT guarantee #1 Google rankings or specific search position',
      'We do NOT promise guaranteed customer counts, calls, or revenue',
      'External infrastructure surges beyond standard usage billed after client notification'
    ]
  }
];

export const initialClients: ClientRecord[] = [
  {
    id: 'client-01',
    clientName: 'Ramesh Sundaram',
    businessName: 'Spice Route Restaurant',
    businessType: 'Restaurant',
    phone: '+91 98421 11223',
    whatsapp: '+91 98421 11223',
    email: 'contact@spiceroute.in',
    address: '42 Heritage Lane, RS Puram, Coimbatore - 641002',
    domain: 'spiceroute.in',
    registrar: 'GoDaddy',
    domainRegistrationDate: '2025-11-15',
    domainExpiryDate: '2026-11-15',
    domainAutoRenew: false,
    vercelProject: 'spice-route-restaurant',
    vercelDeploymentUrl: 'https://spiceroute-restaurant.vercel.app',
    githubRepo: 'https://github.com/viswaas08/spice-route-restaurant',
    currentVersion: 'v2.4.0',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-09-28',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 9999,
    amountPending: 0,
    paymentStatus: 'Fully Paid',
    projectStatus: 'MAINTENANCE',
    projectStartDate: '2025-11-18',
    handoverDate: '2025-11-28',
    maintenancePlanId: 'website-care',
    maintenancePlanName: 'Website Care',
    monthlyMaintenanceAmount: 1499,
    maintenanceStartDate: '2025-12-01',
    nextBillingDate: '2026-11-01',
    maintenancePaymentStatus: 'Current',
    monthlyInfraCost: 280,
    notes: 'South Indian authentic restaurant. Regular menu price updates every season.',
    requirementsSummary: 'Interactive menu, WhatsApp table reservations, mobile-first UX.',
    seo: {
      seoTitle: 'Spice Route — Authentic Chettinad & South Indian Cuisine in Coimbatore',
      metaDescription: 'Dine in or book online at Spice Route. Renowned Chettinad dum biryani, crispy dosas, and heritage wood-fired specialties.',
      primaryCategory: 'Restaurant',
      targetLocation: 'RS Puram, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: true,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: true,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://spiceroute.in',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 340,
      uptimePercentage: 99.94
    }
  },
  {
    id: 'client-02',
    clientName: 'Naveen Kumar & Kavitha N',
    businessName: 'Brew & Bean Cafe',
    businessType: 'Cafe',
    phone: '+91 97890 22334',
    whatsapp: '+91 97890 22334',
    email: 'hello@brewandbean.in',
    address: '12 Green Boulevard, Race Course, Coimbatore - 641018',
    domain: 'brewandbean.in',
    registrar: 'Hostinger',
    domainRegistrationDate: '2026-01-10',
    domainExpiryDate: '2027-01-10',
    domainAutoRenew: false,
    vercelProject: 'brew-and-bean-cafe',
    vercelDeploymentUrl: 'https://brew-and-bean.vercel.app',
    githubRepo: 'https://github.com/viswaas08/brew-bean-cafe',
    currentVersion: 'v1.8.2',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-09-30',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 9999,
    amountPending: 0,
    paymentStatus: 'Fully Paid',
    projectStatus: 'MAINTENANCE',
    projectStartDate: '2026-01-12',
    handoverDate: '2026-01-22',
    maintenancePlanId: 'advanced-care',
    maintenancePlanName: 'Advanced Website Care',
    monthlyMaintenanceAmount: 2999,
    maintenanceStartDate: '2026-02-01',
    nextBillingDate: '2026-11-01',
    maintenancePaymentStatus: 'Current',
    monthlyInfraCost: 350,
    notes: 'Micro-roastery cafe. Very active on local SEO and specialty beans showcase.',
    requirementsSummary: 'Coffee bean origin stories, weekly roast schedule, table reservations.',
    seo: {
      seoTitle: 'Brew & Bean Cafe — Specialty Coffee Roastery & Sourdough',
      metaDescription: 'Single origin Chikmagalur arabica coffee, cold brews, and fresh artisanal sourdough bakes in Race Course Coimbatore.',
      primaryCategory: 'Cafe & Coffee Shop',
      targetLocation: 'Race Course, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: true,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: true,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://brewandbean.in',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 295,
      uptimePercentage: 99.98
    }
  },
  {
    id: 'client-03',
    clientName: 'Deepa Natarajan',
    businessName: 'Sweet Crumbs Bakery',
    businessType: 'Bakery',
    phone: '+91 94432 55667',
    whatsapp: '+91 94432 55667',
    email: 'orders@sweetcrumbs.in',
    address: '88 Crosscut Road, Gandhipuram, Coimbatore - 641012',
    domain: 'sweetcrumbs.in',
    registrar: 'Namecheap',
    domainRegistrationDate: '2026-03-05',
    domainExpiryDate: '2026-10-18', // Expiring soon for demo alert testing (14 days alert)
    domainAutoRenew: false,
    vercelProject: 'sweet-crumbs-bakery',
    vercelDeploymentUrl: 'https://sweet-crumbs.vercel.app',
    githubRepo: 'https://github.com/viswaas08/sweet-crumbs-bakery',
    currentVersion: 'v1.5.0',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-09-15',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 9999,
    amountPending: 0,
    paymentStatus: 'Fully Paid',
    projectStatus: 'MAINTENANCE',
    projectStartDate: '2026-03-08',
    handoverDate: '2026-03-18',
    maintenancePlanId: 'website-care',
    maintenancePlanName: 'Website Care',
    monthlyMaintenanceAmount: 1499,
    maintenanceStartDate: '2026-04-01',
    nextBillingDate: '2026-10-15',
    maintenancePaymentStatus: 'Current',
    monthlyInfraCost: 220,
    notes: 'Custom birthday and wedding cakes. Domain renewal due in mid October.',
    requirementsSummary: 'Cake flavor builder, WhatsApp photo attachment link, morning bread alerts.',
    seo: {
      seoTitle: 'Sweet Crumbs Bakery — Custom Celebration Cakes & Fresh Bakes',
      metaDescription: 'Freshly baked Belgian chocolate truffle cakes, sourdough bread, and custom 2-tier wedding cakes in Gandhipuram.',
      primaryCategory: 'Bakery',
      targetLocation: 'Gandhipuram, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: true,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: true,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://sweetcrumbs.in',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 310,
      uptimePercentage: 99.91
    }
  },
  {
    id: 'client-04',
    clientName: 'Senthil Murugan',
    businessName: 'Urban Mart Supermarket',
    businessType: 'Retail Shop',
    phone: '+91 98940 33445',
    whatsapp: '+91 98940 33445',
    email: 'info@urbanmartdaily.com',
    address: '15 Nehru Nagar, Kalapatti Main Rd, Coimbatore - 641014',
    domain: 'urbanmartdaily.com',
    registrar: 'BigRock',
    domainRegistrationDate: '2026-04-12',
    domainExpiryDate: '2027-04-12',
    domainAutoRenew: false,
    vercelProject: 'urban-mart-daily',
    vercelDeploymentUrl: 'https://urban-mart.vercel.app',
    githubRepo: 'https://github.com/viswaas08/urban-mart',
    currentVersion: 'v1.2.0',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-08-20',
    packageId: 'starter',
    packageName: 'Starter Website',
    totalProjectPrice: 4999,
    advanceAmount: 2499,
    remainingAmount: 2500,
    amountPaid: 4999,
    amountPending: 0,
    paymentStatus: 'Fully Paid',
    projectStatus: 'MAINTENANCE',
    projectStartDate: '2026-04-15',
    handoverDate: '2026-04-22',
    maintenancePlanId: 'website-care',
    maintenancePlanName: 'Website Care',
    monthlyMaintenanceAmount: 1499,
    maintenanceStartDate: '2026-05-01',
    nextBillingDate: '2026-11-01',
    maintenancePaymentStatus: 'Current',
    monthlyInfraCost: 190,
    notes: 'Local departmental store. Simple WhatsApp grocery list ordering.',
    requirementsSummary: 'Daily staples pricing, home delivery radius information, fast loading.',
    seo: {
      seoTitle: 'Urban Mart — Fresh Daily Groceries & Home Delivery in Kalapatti',
      metaDescription: 'Organic rice, cold-pressed oils, and household essentials. Send grocery list on WhatsApp for 45-minute delivery.',
      primaryCategory: 'Grocery & Supermarket',
      targetLocation: 'Kalapatti, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: false,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: false,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://urbanmartdaily.com',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 270,
      uptimePercentage: 100.0
    }
  },
  {
    id: 'client-05',
    clientName: 'Pooja Sundaram',
    businessName: 'Glow Studio Salon',
    businessType: 'Salon',
    phone: '+91 96290 88776',
    whatsapp: '+91 96290 88776',
    email: 'contact@glowstudiosalon.in',
    address: '77 West Club Road, Race Course, Coimbatore - 641018',
    domain: 'glowstudiosalon.in',
    registrar: 'GoDaddy',
    domainRegistrationDate: '2026-05-20',
    domainExpiryDate: '2027-05-20',
    domainAutoRenew: false,
    vercelProject: 'glow-studio-salon',
    vercelDeploymentUrl: 'https://glow-studio.vercel.app',
    githubRepo: 'https://github.com/viswaas08/glow-studio',
    currentVersion: 'v2.1.0',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-09-22',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 9999,
    amountPending: 0,
    paymentStatus: 'Fully Paid',
    projectStatus: 'MAINTENANCE',
    projectStartDate: '2026-05-22',
    handoverDate: '2026-06-01',
    maintenancePlanId: 'advanced-care',
    maintenancePlanName: 'Advanced Website Care',
    monthlyMaintenanceAmount: 2999,
    maintenanceStartDate: '2026-06-15',
    nextBillingDate: '2026-10-25',
    maintenancePaymentStatus: 'Current',
    monthlyInfraCost: 310,
    notes: 'Luxury beauty salon and bridal styling lounge. Heavy photo traffic.',
    requirementsSummary: 'Bridal rate cards, service packages, online appointment booking form.',
    seo: {
      seoTitle: 'Glow Studio — Luxury Salon & Bridal Lounge in Coimbatore',
      metaDescription: 'Organic hair therapies, HD bridal makeup, and keratin treatments by certified senior cosmetologists.',
      primaryCategory: 'Beauty Salon & Spa',
      targetLocation: 'Race Course, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: true,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: true,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://glowstudiosalon.in',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 380,
      uptimePercentage: 99.95
    }
  },
  {
    id: 'client-06',
    clientName: 'Vikramadityan C',
    businessName: 'Forge Fitness Gym',
    businessType: 'Gym',
    phone: '+91 99440 99881',
    whatsapp: '+91 99440 99881',
    email: 'coach@forgefitness.in',
    address: '24 Avinashi Road, Peelamedu, Coimbatore - 641004',
    domain: 'forgefitness.in',
    registrar: 'Namecheap',
    domainRegistrationDate: '2026-06-14',
    domainExpiryDate: '2027-06-14',
    domainAutoRenew: false,
    vercelProject: 'forge-fitness-gym',
    vercelDeploymentUrl: 'https://forge-fitness.vercel.app',
    githubRepo: 'https://github.com/viswaas08/forge-fitness',
    currentVersion: 'v1.4.1',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-09-10',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 9999,
    amountPending: 0,
    paymentStatus: 'Fully Paid',
    projectStatus: 'MAINTENANCE',
    projectStartDate: '2026-06-18',
    handoverDate: '2026-06-28',
    maintenancePlanId: 'website-care',
    maintenancePlanName: 'Website Care',
    monthlyMaintenanceAmount: 1499,
    maintenanceStartDate: '2026-07-01',
    nextBillingDate: '2026-11-01',
    maintenancePaymentStatus: 'Current',
    monthlyInfraCost: 260,
    notes: 'Strength & conditioning gym. Generates leads through Free 1-Day Trial passes.',
    requirementsSummary: 'Membership fee transparency, coach profiles, equipment gallery.',
    seo: {
      seoTitle: 'Forge Fitness Gym — Strength & Conditioning in Peelamedu',
      metaDescription: 'State-of-the-art gym with certified coaches, powerlifting platforms, and personal training. Get your free 1-day pass.',
      primaryCategory: 'Gym & Fitness Centre',
      targetLocation: 'Peelamedu, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: true,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: true,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://forgefitness.in',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 315,
      uptimePercentage: 99.97
    }
  },
  {
    id: 'client-07',
    clientName: 'Dr. K. Swaminathan',
    businessName: 'CarePoint Family Clinic',
    businessType: 'Clinic',
    phone: '+91 94420 12345',
    whatsapp: '+91 94420 12345',
    email: 'care@carepointclinic.org',
    address: '18 Thadagam Road, Saibaba Colony, Coimbatore - 641011',
    domain: 'carepointclinic.org',
    registrar: 'GoDaddy',
    domainRegistrationDate: '2026-07-02',
    domainExpiryDate: '2027-07-02',
    domainAutoRenew: false,
    vercelProject: 'carepoint-family-clinic',
    vercelDeploymentUrl: 'https://carepoint-clinic.vercel.app',
    githubRepo: 'https://github.com/viswaas08/carepoint-clinic',
    currentVersion: 'v1.6.0',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-09-20',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 9999,
    amountPending: 0,
    paymentStatus: 'Fully Paid',
    projectStatus: 'MAINTENANCE',
    projectStartDate: '2026-07-05',
    handoverDate: '2026-07-16',
    maintenancePlanId: 'advanced-care',
    maintenancePlanName: 'Advanced Website Care',
    monthlyMaintenanceAmount: 2999,
    maintenanceStartDate: '2026-08-01',
    nextBillingDate: '2026-11-01',
    maintenancePaymentStatus: 'Current',
    monthlyInfraCost: 290,
    notes: 'Outpatient clinic. Doctor consultation slots and appointment notifications.',
    requirementsSummary: 'Doctor schedules, ethical medical disclaimers, WhatsApp slot requests.',
    seo: {
      seoTitle: 'CarePoint Clinic — General Medicine & Pediatric Care in Saibaba Colony',
      metaDescription: 'Trusted outpatient clinic with senior general physicians and pediatricians. Request consultation slots online.',
      primaryCategory: 'Medical Clinic',
      targetLocation: 'Saibaba Colony, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: true,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: true,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://carepointclinic.org',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 330,
      uptimePercentage: 100.0
    }
  },
  {
    id: 'client-08',
    clientName: 'S. Ramanathan M.Sc., B.Ed.',
    businessName: 'BrightPath Academy',
    businessType: 'Tuition Centre',
    phone: '+91 98435 67890',
    whatsapp: '+91 98435 67890',
    email: 'admin@brightpathtuition.com',
    address: '33 Trichy Road, Singanallur, Coimbatore - 641005',
    domain: 'brightpathtuition.com',
    registrar: 'Hostinger',
    domainRegistrationDate: '2026-08-01',
    domainExpiryDate: '2026-10-25', // Expiring in ~21 days for alert tracking
    domainAutoRenew: false,
    vercelProject: 'brightpath-academy',
    vercelDeploymentUrl: 'https://brightpath-tuition.vercel.app',
    githubRepo: 'https://github.com/viswaas08/brightpath-tuition',
    currentVersion: 'v1.0.0',
    deploymentStatus: 'Ready',
    lastDeploymentDate: '2026-09-02',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 4999,
    amountPending: 5000,
    paymentStatus: 'Pending Final',
    projectStatus: 'CLIENT REVIEW',
    projectStartDate: '2026-08-15',
    maintenancePlanId: 'none',
    maintenancePlanName: 'None',
    monthlyMaintenanceAmount: 0,
    maintenancePaymentStatus: 'N/A',
    monthlyInfraCost: 200,
    notes: 'Secondary & Higher Secondary coaching centre. Final review before live domain switch.',
    requirementsSummary: 'Grade 9–12 syllabus, faculty credentials, free 2-day trial booking.',
    seo: {
      seoTitle: 'BrightPath Academy — CBSE & State Board Tuition in Singanallur',
      metaDescription: 'Concept-oriented math and science tuition for classes 8 to 12. Book a free 2-day classroom trial.',
      primaryCategory: 'Education & Coaching',
      targetLocation: 'Singanallur, Coimbatore',
      hasSitemap: true,
      searchConsoleVerified: false,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: false,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://brightpathtuition.com',
      httpStatus: 200,
      sslActive: true,
      lastChecked: '2026-10-04',
      responseTimeMs: 360,
      uptimePercentage: 99.85
    }
  },
  {
    id: 'client-09',
    clientName: 'Ganesh Venkatesan',
    businessName: 'Venkateswara Auto Spares & Garage',
    businessType: 'Local Service',
    phone: '+91 97870 44556',
    whatsapp: '+91 97870 44556',
    email: 'support@venkateswaraautos.in',
    address: '102 Mettupalayam Rd, RS Puram, Coimbatore - 641002',
    domain: 'venkateswaraautos.in',
    registrar: 'GoDaddy',
    domainRegistrationDate: '2026-09-10',
    domainExpiryDate: '2027-09-10',
    domainAutoRenew: false,
    vercelProject: 'venkateswara-auto-spares',
    vercelDeploymentUrl: 'https://venkateswara-autos.vercel.app',
    githubRepo: 'https://github.com/viswaas08/venkateswara-autos',
    currentVersion: 'v0.9.0',
    deploymentStatus: 'Building',
    lastDeploymentDate: '2026-10-02',
    packageId: 'starter',
    packageName: 'Starter Website',
    totalProjectPrice: 4999,
    advanceAmount: 2499,
    remainingAmount: 2500,
    amountPaid: 2499,
    amountPending: 2500,
    paymentStatus: 'Advance Paid',
    projectStatus: 'DEVELOPMENT',
    projectStartDate: '2026-09-25',
    maintenancePlanId: 'none',
    maintenancePlanName: 'None',
    monthlyMaintenanceAmount: 0,
    maintenancePaymentStatus: 'N/A',
    monthlyInfraCost: 150,
    notes: '2-wheeler mechanical service and genuine spare parts retailer. Site currently in development.',
    requirementsSummary: 'Emergency roadside contact button, spare brands catalogue, Google Maps pinpoint.',
    seo: {
      seoTitle: 'Venkateswara Auto Spares — Genuine Two Wheeler Parts & Service',
      metaDescription: 'OEM motorcycle spares, periodic oil service, and electrical repairs in RS Puram Coimbatore.',
      primaryCategory: 'Auto Repair & Spares',
      targetLocation: 'Mettupalayam Rd, Coimbatore',
      hasSitemap: false,
      searchConsoleVerified: false,
      googleBusinessProfileLinked: false,
      mobileResponsiveCheck: true,
      robotsTxtCheck: true,
      schemaMarkupCheck: false,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://venkateswaraautos.in',
      httpStatus: 200,
      sslActive: false,
      lastChecked: '2026-10-04',
      responseTimeMs: 0,
      uptimePercentage: 0
    }
  },
  {
    id: 'client-10',
    clientName: 'Shalini Pradeep',
    businessName: 'Kovai Dental Studio',
    businessType: 'Clinic',
    phone: '+91 98422 77889',
    whatsapp: '+91 98422 77889',
    email: 'smile@kovaidental.com',
    address: '56 100 Feet Road, Tatabad, Coimbatore - 641012',
    domain: 'kovaidental.com',
    registrar: 'Namecheap',
    domainRegistrationDate: '2026-09-18',
    domainExpiryDate: '2027-09-18',
    domainAutoRenew: false,
    vercelProject: 'kovai-dental-studio',
    vercelDeploymentUrl: '',
    githubRepo: 'https://github.com/viswaas08/kovai-dental',
    currentVersion: 'v0.1.0',
    deploymentStatus: 'Inactive',
    lastDeploymentDate: '',
    packageId: 'business',
    packageName: 'Business Website',
    totalProjectPrice: 9999,
    advanceAmount: 4999,
    remainingAmount: 5000,
    amountPaid: 4999,
    amountPending: 5000,
    paymentStatus: 'Advance Paid',
    projectStatus: 'ADVANCE PAID',
    projectStartDate: '2026-10-01',
    maintenancePlanId: 'website-care',
    maintenancePlanName: 'Website Care',
    monthlyMaintenanceAmount: 1499,
    maintenancePaymentStatus: 'N/A',
    monthlyInfraCost: 0,
    notes: 'Advance received via UPI. Currently gathering clinic photos and doctor certificates.',
    requirementsSummary: 'Painless dentistry services, smile gallery, digital appointment request.',
    seo: {
      seoTitle: 'Kovai Dental Studio — Modern Cosmetic & Implant Dentistry',
      metaDescription: 'Laser teeth whitening, dental implants, and pediatric oral care in Tatabad Coimbatore.',
      primaryCategory: 'Dental Clinic',
      targetLocation: 'Tatabad, Coimbatore',
      hasSitemap: false,
      searchConsoleVerified: false,
      googleBusinessProfileLinked: true,
      mobileResponsiveCheck: true,
      robotsTxtCheck: false,
      schemaMarkupCheck: false,
      napConsistencyCheck: true
    },
    health: {
      productionUrl: 'https://kovaidental.com',
      httpStatus: 0,
      sslActive: false,
      lastChecked: '2026-10-04',
      responseTimeMs: 0,
      uptimePercentage: 0
    }
  }
];

export const initialLeads: LeadRecord[] = [
  {
    id: 'lead-01',
    name: 'Anand Krishnan',
    businessName: 'Royal Treats Sweet Shop',
    businessType: 'Bakery',
    phone: '+91 98430 77112',
    whatsapp: '+91 98430 77112',
    email: 'anand@royaltreats.com',
    source: 'Website',
    interestedPackage: 'Business Website (₹9,999)',
    estimatedValue: 9999,
    status: 'Meeting',
    notes: 'Interested in digital sweet box ordering for Diwali season. Meeting scheduled for Tuesday.',
    dateContacted: '2026-10-01',
    followUpDate: '2026-10-07'
  },
  {
    id: 'lead-02',
    name: 'Praveen Chandran',
    businessName: 'Apex Crossfit Studio',
    businessType: 'Gym',
    phone: '+91 97880 33441',
    whatsapp: '+91 97880 33441',
    email: 'praveen@apexcrossfit.in',
    source: 'Local Outreach',
    interestedPackage: 'Business Website (₹9,999)',
    estimatedValue: 9999,
    status: 'Proposal Sent',
    notes: 'Sent PDF proposal with Forge Fitness gym demo reference. Client reviewing pricing with partner.',
    dateContacted: '2026-09-29',
    followUpDate: '2026-10-06'
  },
  {
    id: 'lead-03',
    name: 'Dr. Meenakshi S',
    businessName: 'AyurSree Ayurvedic Centre',
    businessType: 'Clinic',
    phone: '+91 94433 88990',
    whatsapp: '+91 94433 88990',
    email: 'ayursree@gmail.com',
    source: 'WhatsApp',
    interestedPackage: 'Business Website (₹9,999)',
    estimatedValue: 12998, // Website + Advanced Care
    status: 'Meeting',
    notes: 'Inquired through WhatsApp floating button. Wants treatment rate card & doctor consultations.',
    dateContacted: '2026-10-03',
    followUpDate: '2026-10-05'
  },
  {
    id: 'lead-04',
    name: 'Karthika Devi',
    businessName: 'Aura Organic Salon & Spa',
    businessType: 'Salon',
    phone: '+91 96550 44112',
    whatsapp: '+91 96550 44112',
    email: 'auraspa@gmail.com',
    source: 'Referral',
    interestedPackage: 'Business Website (₹9,999)',
    estimatedValue: 9999,
    status: 'Won',
    notes: 'Referred by Glow Studio. Agreed to ₹9,999 Business package with 50% advance payment.',
    dateContacted: '2026-09-24',
    followUpDate: '2026-10-02'
  },
  {
    id: 'lead-05',
    name: 'Muthusamy K',
    businessName: 'Sri Amman Timber & Hardware',
    businessType: 'Retail Shop',
    phone: '+91 98425 22339',
    whatsapp: '+91 98425 22339',
    email: 'info@ammantimbers.com',
    source: 'Local Outreach',
    interestedPackage: 'Starter Website (₹4,999)',
    estimatedValue: 4999,
    status: 'Replied',
    notes: 'Wants a simple 2-page catalog with plywood dimensions, hardware items, and telephone contacts.',
    dateContacted: '2026-10-02',
    followUpDate: '2026-10-08'
  },
  {
    id: 'lead-06',
    name: 'Suresh Babu',
    businessName: 'Coimbatore Chess Academy',
    businessType: 'Tuition Centre',
    phone: '+91 94431 00223',
    whatsapp: '+91 94431 00223',
    email: 'coach@coimbatorechess.com',
    source: 'Website',
    interestedPackage: 'Starter Website (₹4,999)',
    estimatedValue: 4999,
    status: 'New',
    notes: 'Submitted enquiry through portfolio contact form. Follow up with WhatsApp message.',
    dateContacted: '2026-10-04',
    followUpDate: '2026-10-05'
  }
];

export const adminCredentials = {
  // Default demo access for local business dashboard
  username: import.meta.env.VITE_ADMIN_USER || 'admin',
  passwordHashDemo: 'admin2026', // In a production server, replaced with bcrypt salt & hash
  role: 'Agency Owner',
  agencyName: 'Viswaa Web Agency Systems'
};
